print("enter the radius of the circle: ")
a = float(input())
b = int(2)
c = int(3.14)
print("the circumference of the given circle is ")
print(a*b*c)
print("            ")
print("the area of the given circle is ")
print(c*c*a)
